Repository ntls-io/nautilus-wallet, pull requests merged in 2022-10, with the labels that each got.

#376 ci(web-client): remove chromatic
  .github/workflows/web-client.yaml
  web-client/package-lock.json
  web-client/package.json
  web-client/src/app/components/pay-amount-confirm/pay-amount-confirm.component.stories.ts
  web-client/src/app/components/pay-amount-form/pay-amount-form.component.stories.ts
  web-client/src/app/components/pay/pay.component.stories.ts
  web-client/src/app/components/pin-entry/pin-entry.component.stories.ts
  web-client/src/app/components/pure-pay-page/pure-pay-page.component.stories.ts
  web-client/src/app/views/pay/pay.page.stories.ts
Labels: CI/CD, maintenance

#384 style(web-client): fix typo on security questions
  web-client/src/app/components/security-questions/security-questions.component.ts
Labels: small

#378 fix(web-client): macth onfido country's bg color
  web-client/src/app/views/kyc/onfido-widget/onfido-widget.component.scss
Labels: small

#390 Fix-swiper-overflow
  web-client/src/app/views/register/register.page.html
Labels: small

#392 feat(web-client): hide kyc for bhutan
  web-client/src/app/state/session.query.ts
  web-client/src/app/views/wallet/wallet.page.html
Labels: M: web-client, small

#393 build(web-client): update plugins & dependencies
  web-client/angular.json
  web-client/package-lock.json
  web-client/package.json
  web-client/src/app/views/kyc/onfido-widget/onfido-widget.component.ts
Labels: M: web-client, maintenance
